[project]
name = "ram-python"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "jsonschema>=4.25.1",
    "pytest>=8.4.2",
    "pytest-cov>=6.0.0",
    "requests>=2.32.5",
]
